# Generated by Django 5.0.4 on 2024-04-13 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('worker', 'Worker')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('worker', 'Worker')], default='worker', max_length=10),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
